local M = {}

---@param colors table
---@param config ThemeConfig
---@return table<string, HighlightDefinition>
function M.get(colors, config)
  -- vscode.nvim kind mapping:
  -- function/method → pink, constructor/class/enum → ui orange,
  -- variable/field/property/interface → light blue, keyword/snippet/event → dark yellow
  return {
    -- Blink Cmp
    BlinkCmpMenu = { link = "Pmenu" },
    BlinkCmpMenuBorder = { link = "FloatBorder" },
    BlinkCmpMenuSelection = { link = "PmenuSel" },
    BlinkCmpScrollBarThumb = { link = "PmenuThumb" },
    BlinkCmpScrollBarGutter = { link = "PmenuSbar" },
    BlinkCmpLabel = { link = "ThemeFg1" },
    BlinkCmpLabelDeprecated = { fg = colors.cursor_dark, strikethrough = config.strikethrough },
    BlinkCmpLabelMatch = { link = "ThemeMediumBlueBold" },
    BlinkCmpLabelDetail = { link = "ThemeFg0" },
    BlinkCmpLabelDescription = { link = "ThemeFg0" },
    BlinkCmpKind = { link = "ThemeFg0" },
    BlinkCmpSource = { link = "ThemeFg0" },
    BlinkCmpGhostText = { fg = colors.context_current },
    BlinkCmpDoc = { link = "NormalFloat" },
    BlinkCmpDocBorder = { link = "FloatBorder" },
    BlinkCmpDocSeparator = { link = "NormalFloat" },
    BlinkCmpDocCursorLine = { link = "Visual" },
    BlinkCmpSignatureHelp = { link = "NormalFloat" },
    BlinkCmpSignatureHelpBorder = { link = "FloatBorder" },
    BlinkCmpSignatureHelpActiveParameter = { link = "LspSignatureActiveParameter" },
    BlinkCmpKindText = { link = "ThemeFg0" },
    BlinkCmpKindMethod = { link = "ThemePink" },
    BlinkCmpKindFunction = { link = "ThemePink" },
    BlinkCmpKindConstructor = { fg = colors.ui_orange },
    BlinkCmpKindField = { link = "@variable.member" },
    BlinkCmpKindVariable = { link = "@variable.member" },
    BlinkCmpKindClass = { link = "BlinkCmpKindConstructor" },
    BlinkCmpKindInterface = { link = "ThemeLightBlue" },
    BlinkCmpKindModule = { link = "BlinkCmpKindClass" },
    BlinkCmpKindProperty = { link = "BlinkCmpKindField" },
    BlinkCmpKindUnit = { link = "BlinkCmpKindField" },
    BlinkCmpKindValue = { link = "@variable.member" },
    BlinkCmpKindEnum = { link = "BlinkCmpKindConstructor" },
    BlinkCmpKindKeyword = { link = "ThemeDarkYellow" },
    BlinkCmpKindSnippet = { link = "ThemeDarkYellow" },
    BlinkCmpKindColor = { link = "ThemeOrange" },
    BlinkCmpKindFile = { link = "@markup.link.url" },
    BlinkCmpKindReference = { link = "@variable.parameter.reference" },
    BlinkCmpKindFolder = { link = "ThemeBlue" },
    BlinkCmpKindEnumMember = { link = "@variable.member" },
    BlinkCmpKindConstant = { link = "@constant" },
    BlinkCmpKindStruct = { link = "@structure" },
    BlinkCmpKindEvent = { link = "ThemeDarkYellow" },
    BlinkCmpKindOperator = { link = "@operator" },
    BlinkCmpKindTypeParameter = { link = "@variable.parameter" },
    BlinkCmpKindCopilot = { link = "ThemeBlueGreen" },
    -- nvim-cmp
    CmpItemAbbr = { link = "ThemeFg1" },
    CmpItemAbbrDeprecated = { fg = colors.cursor_dark, strikethrough = config.strikethrough },
    CmpItemAbbrMatch = { link = "ThemeMediumBlueBold" },
    CmpItemAbbrMatchFuzzy = { link = "ThemeMediumBlueBold" },
    CmpItemMenu = { link = "ThemeFg0" },
    CmpItemKind = { link = "Pmenu" },
    CmpItemKindText = { link = "ThemeLightBlue" },
    CmpItemKindVariable = { link = "ThemeLightBlue" },
    CmpItemKindMethod = { link = "ThemePink" },
    CmpItemKindFunction = { link = "ThemePink" },
    CmpItemKindConstructor = { fg = colors.ui_orange },
    CmpItemKindUnit = { link = "ThemeFg1" },
    CmpItemKindField = { link = "@variable.member" },
    CmpItemKindClass = { link = "CmpItemKindConstructor" },
    CmpItemKindInterface = { link = "ThemeLightBlue" },
    CmpItemKindModule = { link = "CmpItemKindKeyword" },
    CmpItemKindProperty = { link = "ThemeFg1" },
    CmpItemKindValue = { link = "@variable.member" },
    CmpItemKindEnum = { link = "@variable.member" },
    CmpItemKindOperator = { link = "@operator" },
    CmpItemKindKeyword = { link = "ThemeFg1" },
    CmpItemKindEvent = { link = "@constant" },
    CmpItemKindReference = { link = "@variable.parameter.reference" },
    CmpItemKindColor = { link = "ThemeOrange" },
    CmpItemKindSnippet = { link = "@text" },
    CmpItemKindFile = { link = "@markup.link.url" },
    CmpItemKindFolder = { link = "@markup.link.url" },
    CmpItemKindEnumMember = { link = "@variable.member" },
    CmpItemKindConstant = { link = "@constant" },
    CmpItemKindStruct = { link = "@structure" },
    CmpItemKindTypeParameter = { link = "@variable.parameter" },
  }
end

return M
