local M = {}

---@param colors table
---@param config ThemeConfig
---@return table<string, HighlightDefinition>
function M.get(colors, config)
  local bg0 = not config.transparent_mode and colors.bg0 or nil
  local bg2 = not config.transparent_mode and colors.bg2 or nil
  local bg3 = not config.transparent_mode and colors.bg3 or nil
  local bg4 = not config.transparent_mode and colors.bg4 or nil
  local bg_left_light = not config.transparent_mode and colors.bg_left_light or nil

  return {
    MiniAnimateCursor = { reverse = true, nocombine = true },
    MiniAnimateNormalFloat = { link = "NormalFloat" },
    MiniClueBorder = { link = "FloatBorder" },
    MiniClueDescGroup = { link = "DiagnosticFloatingWarn" },
    MiniClueDescSingle = { link = "NormalFloat" },
    MiniClueNextKey = { link = "DiagnosticFloatingHint" },
    MiniClueNextKeyWithPostkeys = { link = "DiagnosticFloatingError" },
    MiniClueSeparator = { link = "DiagnosticFloatingInfo" },
    MiniClueTitle = { link = "FloatTitle" },
    MiniCompletionActiveParameter = { underline = config.underline },
    MiniCursorword = { bg = colors.popup_highlight_gray },
    MiniCursorwordCurrent = { bg = colors.popup_highlight_gray },
    MiniDepsChangeAdded = { link = "ThemeGitAdded" },
    MiniDepsChangeRemoved = { link = "ThemeGitDeleted" },
    MiniDepsHint = { link = "DiagnosticHint" },
    MiniDepsInfo = { link = "DiagnosticInfo" },
    MiniDepsMsgBreaking = { link = "DiagnosticWarn" },
    MiniDepsPlaceholder = { link = "Comment" },
    MiniDepsTitle = { link = "Title" },
    MiniDepsTitleError = { link = "DiffDelete" },
    MiniDepsTitleSame = { link = "DiffChange" },
    MiniDepsTitleUpdate = { link = "DiffAdd" },
    MiniDiffOverAdd = { link = "DiffAdd" },
    MiniDiffOverChange = { link = "DiffText" },
    MiniDiffOverContext = { link = "DiffChange" },
    MiniDiffOverDelete = { link = "DiffDelete" },
    MiniDiffSignAdd = { link = "ThemeGreenSign" },
    MiniDiffSignChange = { link = "ThemeYellowSign" },
    MiniDiffSignDelete = { link = "ThemeRedSign" },
    MiniFilesBorder = { link = "FloatBorder" },
    MiniFilesBorderModified = { link = "DiagnosticFloatingWarn" },
    MiniFilesCursorLine = { link = "PmenuSel" },
    MiniFilesDirectory = { link = "Directory" },
    MiniFilesFile = { link = "ThemeFg1" },
    MiniFilesNormal = { link = "NormalFloat" },
    MiniFilesTitle = { link = "FloatTitle" },
    MiniFilesTitleFocused = { link = "ThemeBlueBold" },
    MiniHipatternsFixme = { fg = colors.bg0, bg = colors.red, bold = config.bold },
    MiniHipatternsHack = { fg = colors.bg0, bg = colors.yellow_orange, bold = config.bold },
    MiniHipatternsNote = { fg = colors.bg0, bg = colors.blue_green, bold = config.bold },
    MiniHipatternsTodo = { fg = colors.bg0, bg = colors.blue, bold = config.bold },
    MiniIconsAzure = { link = "ThemeBlue" },
    MiniIconsBlue = { link = "ThemeMediumBlue" },
    MiniIconsCyan = { link = "ThemeBlueGreen" },
    MiniIconsGreen = { link = "ThemeGreen" },
    MiniIconsGrey = { link = "ThemeFg1" },
    MiniIconsOrange = { link = "ThemeRed" },
    MiniIconsPurple = { link = "ThemePink" },
    MiniIconsRed = { link = "ThemeRed" },
    MiniIconsYellow = { link = "ThemeDarkYellow" },
    MiniIndentscopeSymbol = { fg = colors.context_current, nocombine = true },
    MiniIndentscopeSymbolOff = { link = "ThemeYellowOrange" },
    MiniJump = { link = "Search" },
    MiniJump2dDim = { link = "ThemeGray" },
    MiniJump2dSpot = { fg = colors.dark_yellow, bold = config.bold, nocombine = true },
    MiniJump2dSpotAhead = { fg = colors.blue_green, nocombine = true },
    MiniJump2dSpotUnique = { fg = colors.ui_orange, bold = config.bold, nocombine = true },
    MiniMapNormal = { link = "NormalFloat" },
    MiniMapSymbolCount = { link = "Special" },
    MiniMapSymbolLine = { link = "Title" },
    MiniMapSymbolView = { link = "Delimiter" },
    MiniNotifyBorder = { link = "FloatBorder" },
    MiniNotifyNormal = { link = "NormalFloat" },
    MiniNotifyTitle = { link = "FloatTitle" },
    MiniOperatorsExchangeFrom = { link = "IncSearch" },
    MiniPickBorder = { link = "FloatBorder" },
    MiniPickBorderBusy = { link = "DiagnosticFloatingWarn" },
    MiniPickBorderText = { link = "FloatTitle" },
    MiniPickIconDirectory = { link = "Directory" },
    MiniPickIconFile = { link = "MiniPickNormal" },
    MiniPickHeader = { link = "DiagnosticFloatingHint" },
    MiniPickMatchCurrent = { link = "PmenuSel" },
    MiniPickMatchMarked = { link = "Visual" },
    MiniPickMatchRanges = { link = "ThemeMediumBlueBold" },
    MiniPickNormal = { link = "NormalFloat" },
    MiniPickPreviewLine = { link = "CursorLine" },
    MiniPickPreviewRegion = { link = "IncSearch" },
    MiniPickPrompt = { link = "DiagnosticFloatingInfo" },
    MiniStarterCurrent = { nocombine = true },
    MiniStarterFooter = { link = "ThemeGray" },
    MiniStarterHeader = { link = "ThemeBlue" },
    MiniStarterInactive = { link = "Comment" },
    MiniStarterItem = { link = "Normal" },
    MiniStarterItemBullet = { link = "Delimiter" },
    MiniStarterItemPrefix = { link = "ThemePink" },
    MiniStarterSection = { link = "ThemeYellowOrange" },
    MiniStarterQuery = { link = "MoreMsg" },
    MiniStatuslineDevinfo = { fg = colors.fg1, bg = bg_left_light },
    MiniStatuslineFileinfo = { fg = colors.fg1, bg = bg_left_light },
    MiniStatuslineFilename = { fg = colors.fg1, bg = bg4 },
    MiniStatuslineInactive = { fg = colors.fg1, bg = bg2 },
    MiniStatuslineModeCommand = { fg = colors.bg0, bg = colors.light_red, bold = config.bold },
    MiniStatuslineModeInsert = { fg = colors.bg0, bg = colors.light_blue, bold = config.bold },
    MiniStatuslineModeNormal = { fg = colors.bg0, bg = colors.light_green, bold = config.bold },
    MiniStatuslineModeOther = { fg = colors.bg0, bg = colors.blue_green, bold = config.bold },
    MiniStatuslineModeReplace = { fg = colors.bg0, bg = colors.yellow_orange, bold = config.bold },
    MiniStatuslineModeVisual = { fg = colors.bg0, bg = colors.pink, bold = config.bold },
    MiniSurround = { link = "IncSearch" },
    MiniTablineCurrent = { fg = colors.fg1, bg = bg0, bold = config.bold, reverse = config.invert_tabline },
    MiniTablineFill = { link = "TabLineFill" },
    MiniTablineHidden = { fg = colors.muted, bg = bg3, reverse = config.invert_tabline },
    MiniTablineModifiedCurrent = {
      fg = colors.yellow_orange,
      bg = bg0,
      bold = config.bold,
      reverse = config.invert_tabline,
    },
    MiniTablineModifiedHidden = { fg = colors.yellow_orange, bg = bg3, reverse = config.invert_tabline },
    MiniTablineModifiedVisible = { fg = colors.yellow_orange, bg = bg0, reverse = config.invert_tabline },
    MiniTablineTabpagesection = { fg = colors.fg1, bg = bg3 },
    MiniTablineVisible = { fg = colors.muted, bg = bg0, reverse = config.invert_tabline },
    MiniTestEmphasis = { bold = config.bold },
    MiniTestFail = { link = "ThemeRedBold" },
    MiniTestPass = { link = "ThemeBlueGreenBold" },
    MiniTrailspace = { bg = colors.red },
  }
end

return M
